-- MySQL Script generated by MySQL Workbench
-- Fri Nov 30 22:27:22 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sanepar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sanepar` ;

-- -----------------------------------------------------
-- Schema sanepar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sanepar` DEFAULT CHARACTER SET utf8 ;
USE `sanepar` ;

-- -----------------------------------------------------
-- Table `sanepar`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sanepar`.`estado` ;

CREATE TABLE IF NOT EXISTS `sanepar`.`estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nomeEstado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`),
  UNIQUE INDEX `idEstado_UNIQUE` (`idEstado` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanepar`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sanepar`.`cidade` ;

CREATE TABLE IF NOT EXISTS `sanepar`.`cidade` (
  `idCidade` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeCidade` VARCHAR(45) NOT NULL,
  `idEstado` INT NOT NULL,
  PRIMARY KEY (`idCidade`),
  UNIQUE INDEX `idCidade_UNIQUE` (`idCidade` ASC),
  INDEX `fk_cidade_estado_idx` (`idEstado` ASC),
  CONSTRAINT `fk_cidade_estado`
    FOREIGN KEY (`idEstado`)
    REFERENCES `sanepar`.`estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanepar`.`rua`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sanepar`.`rua` ;

CREATE TABLE IF NOT EXISTS `sanepar`.`rua` (
  `idRua` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeRua` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRua`),
  UNIQUE INDEX `idEstado_UNIQUE` (`idRua` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanepar`.`bairro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sanepar`.`bairro` ;

CREATE TABLE IF NOT EXISTS `sanepar`.`bairro` (
  `idBairro` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeBairro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBairro`),
  UNIQUE INDEX `idEstado_UNIQUE` (`idBairro` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanepar`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sanepar`.`endereco` ;

CREATE TABLE IF NOT EXISTS `sanepar`.`endereco` (
  `idEndereco` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idCidade` INT UNSIGNED NOT NULL,
  `idRua` INT UNSIGNED NOT NULL,
  `idBairro` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEndereco`),
  UNIQUE INDEX `idEndereco_UNIQUE` (`idEndereco` ASC),
  INDEX `fk_endereco_cidade1_idx` (`idCidade` ASC),
  INDEX `fk_endereco_rua1_idx` (`idRua` ASC),
  INDEX `fk_endereco_bairro1_idx` (`idBairro` ASC),
  CONSTRAINT `fk_endereco_cidade1`
    FOREIGN KEY (`idCidade`)
    REFERENCES `sanepar`.`cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_rua1`
    FOREIGN KEY (`idRua`)
    REFERENCES `sanepar`.`rua` (`idRua`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_bairro1`
    FOREIGN KEY (`idBairro`)
    REFERENCES `sanepar`.`bairro` (`idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanepar`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sanepar`.`cliente` ;

CREATE TABLE IF NOT EXISTS `sanepar`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(45) NOT NULL,
  `documentoCliente` VARCHAR(45) NOT NULL,
  `pessoaJuridica` TINYINT NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanepar`.`email`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sanepar`.`email` ;

CREATE TABLE IF NOT EXISTS `sanepar`.`email` (
  `idEmail` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `enderecoEmail` VARCHAR(45) NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idEmail`),
  UNIQUE INDEX `idEmail_UNIQUE` (`idEmail` ASC),
  INDEX `fk_email_cliente1_idx` (`idCliente` ASC),
  CONSTRAINT `fk_email_cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `sanepar`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanepar`.`telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sanepar`.`telefone` ;

CREATE TABLE IF NOT EXISTS `sanepar`.`telefone` (
  `idTelefone` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numeroTelefone` VARCHAR(15) NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idTelefone`),
  UNIQUE INDEX `idEmail_UNIQUE` (`idTelefone` ASC),
  INDEX `fk_telefone_cliente1_idx` (`idCliente` ASC),
  CONSTRAINT `fk_telefone_cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `sanepar`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanepar`.`enderecoEspecifico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sanepar`.`enderecoEspecifico` ;

CREATE TABLE IF NOT EXISTS `sanepar`.`enderecoEspecifico` (
  `idEnderecoEspecifico` INT NOT NULL AUTO_INCREMENT,
  `cepEndereco` VARCHAR(45) NOT NULL,
  `numeroEndereco` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(80) NULL,
  `idEndereco` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEnderecoEspecifico`),
  UNIQUE INDEX `idEnderecoEspecifico_UNIQUE` (`idEnderecoEspecifico` ASC),
  INDEX `fk_enderecoEspecifico_endereco1_idx` (`idEndereco` ASC),
  CONSTRAINT `fk_enderecoEspecifico_endereco1`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `sanepar`.`endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanepar`.`hidrometro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sanepar`.`hidrometro` ;

CREATE TABLE IF NOT EXISTS `sanepar`.`hidrometro` (
  `idHidrometro` INT NOT NULL AUTO_INCREMENT,
  `idEnderecoEspecifico` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `registroHidrometro` VARCHAR(45) NOT NULL,
  INDEX `fk_enderecoEspecifico_has_cliente_cliente1_idx` (`idCliente` ASC),
  INDEX `fk_enderecoEspecifico_has_cliente_enderecoEspecifico1_idx` (`idEnderecoEspecifico` ASC),
  PRIMARY KEY (`idHidrometro`),
  UNIQUE INDEX `idHidrometro_UNIQUE` (`idHidrometro` ASC),
  CONSTRAINT `fk_enderecoEspecifico_has_cliente_enderecoEspecifico1`
    FOREIGN KEY (`idEnderecoEspecifico`)
    REFERENCES `sanepar`.`enderecoEspecifico` (`idEnderecoEspecifico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enderecoEspecifico_has_cliente_cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `sanepar`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sanepar`.`fatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sanepar`.`fatura` ;

CREATE TABLE IF NOT EXISTS `sanepar`.`fatura` (
  `idFatura` INT NOT NULL AUTO_INCREMENT,
  `mesFatura` VARCHAR(45) NOT NULL,
  `metrosCubicos` INT NOT NULL,
  `custoMetroCubico` FLOAT NOT NULL,
  `esgoto` TINYINT NOT NULL,
  `custoEsgoto` FLOAT NOT NULL DEFAULT 0,
  `idHidrometro` INT NOT NULL,
  PRIMARY KEY (`idFatura`),
  INDEX `fk_fatura_hidrometro1_idx` (`idHidrometro` ASC),
  CONSTRAINT `fk_fatura_hidrometro1`
    FOREIGN KEY (`idHidrometro`)
    REFERENCES `sanepar`.`hidrometro` (`idHidrometro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
